name: Create Crowdin project

on:
  workflow_dispatch:

jobs:
  crowdin-create:
    runs-on: ubuntu-latest
    steps:
      - name: Create crowdin project
        uses: crowdin/github-action@v2
        with:
          command: "project add"
          command_args: '"${GITHUB_REPOSITORY#*/}" -l fr -l es-ES'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
